# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{oa-facebook}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Igor Alexandrov"]
  s.date = %q{2011-02-09}
  s.description = %q{Include this gem into your project with OmniAuth gem and you will get Facebook login in one line of code.}
  s.email = %q{igor.alexandrov@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/oa-facebook.rb",
    "lib/omniauth/facebook.rb",
    "lib/omniauth/strategies/facebook.rb",
    "lib/omniauth/strategies/facebook/view_helper.rb",
    "oa-facebook.gemspec",
    "test/helper.rb",
    "test/test_oa-facebook.rb"
  ]
  s.homepage = %q{http://github.com/igor-alexandrov/oa-facebook}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Facebook OmniAuth module with view helpers}
  s.test_files = [
    "test/helper.rb",
    "test/test_oa-facebook.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oa-core>, ["~> 0.1.4"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<oa-core>, ["~> 0.1.4"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<oa-core>, ["~> 0.1.4"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

